/* PRAGATI PORTFOLIO — EASY UPDATE
   Edit this file to update your portfolio content. No need to change index.html.
*/
const portfolioData={
 profile:{name:'Pragati Anshuman Chandra',shortName:'Pragati',title:'Data Science & Computer Science Student',tagline:'I build practical applications across data science, AI, machine learning and full-stack development.',about:'I am a Data Science and Computer Science student passionate about machine learning, predictive modeling, data analysis and web development. I enjoy turning ideas into practical applications.',location:'Navi Mumbai, India',email:'pragatichandra2323@gmail.com',phone:'+91 9326688099',github:'https://github.com/23f3001930',linkedin:'https://www.linkedin.com/in/193563293',resume:'assets/Pragati-Chandra-Resume.pdf',photo:'assets/pragati-profile.jpeg'},
 education:[
  {year:'2023 — 2027',degree:'B.S. Programming and Data Science',institute:'Indian Institute of Technology Madras',place:'Chennai, India'},
  {year:'2023 — 2027',degree:'B.E. Computer Science',institute:'Mumbai University',place:'Mumbai, India'}
 ],
 projects:[
  {title:'Placement Portal Application',category:'FULL STACK',featured:true,description:'A full-stack placement portal for students, companies and administrators, with secure access, placement drives, applications and interview workflows.',detail:'<b>Used:</b> Flask, Vue.js, SQLAlchemy, SQLite, REST APIs, Bootstrap 5, Celery & Redis. <b>Security:</b> JWT Authentication with 3 roles — Admin, Company and Student — and role-based authorization.',tags:['Flask','Vue.js','JWT','SQLAlchemy','SQLite','Celery','Redis'],links:[{label:'Watch video',url:'https://drive.google.com/file/d/1dwH3Tz1gdhoQyBF1Jgm-qrdbqwCkS7Ph/view?usp=sharing',external:true},{label:'View report',url:'https://drive.google.com/file/d/1p6gCd-C-73wNlswIfisLnOi55oMrSpEk/view?usp=sharing',external:true},{label:'Project files',url:'assets/Placement-Portal-Application.zip',download:true}]},
  {title:'Vehicle Parking App',category:'FLASK',description:'A Flask-based web app for managing vehicle parking with authentication, booking and data visualization.',detail:'<b>Used:</b> Python, Flask, SQLite and data visualization to manage users, parking availability and booking activity.',tags:['Python','Flask','SQLite','Authentication','Booking'],links:[{label:'Watch video',url:'https://drive.google.com/file/d/1gLs345812T5FCsKHd3C2h5OLBwNJzZyx/view?usp=sharing',external:true}]},
  {title:'RAG System for Tools in Data Science (IIT Madras)',category:'RAG / AI',description:'A Retrieval-Augmented Generation (RAG) system that answers student questions using Discourse forum posts and course content from the Tools in Data Science course.',detail:'<b>Used:</b> preprocess.py for chunking Discourse and Markdown data and generating embeddings, FastAPI for the /query endpoint, and SQLite for the knowledge base.',tags:['Python','RAG','FastAPI','Embeddings','SQLite','TDS'],links:[{label:'GitHub project',url:'https://github.com/23f3001930/TDS11',external:true}]},
  {title:'Vehicle CO₂ Emissions Prediction',category:'ML',description:'An ML-based web app that predicts vehicle CO₂ emissions using regression models and Streamlit.',detail:'<b>Used:</b> Python, Scikit-learn and Streamlit to build a predictive model and interactive application.',tags:['Python','Scikit-learn','Streamlit','Regression'],links:[{label:'GitHub project',url:'https://github.com/23f3001930/Vehicle_CO2_Emissions_prediction',external:true}]},
  {title:'Notes App',category:'FULL STACK',description:'A Notes App using MongoDB for efficient data storage and management.',detail:'<b>Used:</b> MongoDB with create, view, update and delete features and backend APIs for reliable, persistent note management.',tags:['MongoDB','CRUD','Backend APIs','Notes'],links:[{label:'GitHub project',url:'https://github.com/23f3001930/mongo-notes-app-pro',external:true}]},
  {title:'Kaggle Project 01',category:'KAGGLE',description:'Data science project showcasing practical analysis and machine-learning work on Kaggle.',detail:'<b>Used:</b> Kaggle, Python and data-science workflows for practical dataset analysis and machine-learning work.',tags:['Kaggle','Python','Data Science'],links:[{label:'Watch video',url:'https://drive.google.com/file/d/1BNpPBrcp6Wypvzu5HFlYYBDs3WV-2c2a/view?usp=sharing',external:true}]},
  {title:'Kaggle Project 02',category:'KAGGLE',description:'Kaggle project highlighting data analysis, modeling and practical problem solving.',detail:'<b>Used:</b> Kaggle, Python and machine-learning workflows for analysis, modeling and practical problem solving.',tags:['Kaggle','Python','Machine Learning'],links:[{label:'Watch video',url:'https://drive.google.com/file/d/1hFtdvyCuYGeFxceIVFdct550hNFvh0ks/view?usp=sharing',external:true}]},
  {title:'Kaggle Project 03',category:'KAGGLE',description:'Kaggle project demonstrating hands-on work with datasets, analysis and machine learning.',detail:'<b>Used:</b> Kaggle, Python and data-analysis workflows for hands-on dataset analysis and machine learning.',tags:['Kaggle','Data Analysis','Python'],links:[{label:'Watch video',url:'https://drive.google.com/file/d/1Odjunv1m5CUQCahchbqa10RAm5Eq1C2d/view?usp=sharing',external:true}]}
 ],
 skills:[
  ['Programming Languages','Python · SQL · HTML · CSS · JavaScript'],['Frameworks & Libraries','Flask · Streamlit · Scikit-learn · Pandas · NumPy · Matplotlib · Seaborn · Bootstrap'],['Databases','SQLite · MySQL · SQLAlchemy ORM · MongoDB'],['Tools & Platforms','Git & GitHub · REST APIs · Jinja Templating · Vue.js'],['Backend & Security','JWT Authentication · Role-based Authorization · Celery · Redis · REST APIs'],['Data & AI','Machine Learning · Predictive Modeling · Data Analysis · Google Generative AI']
 ],
 certificates:[
  {title:'IIT Madras — Foundational Level',issuer:'IIT MADRAS',links:[['Open certificate','https://drive.google.com/file/d/1xlUuXk1ssgx1MBEUkSbOYwqu_a6tnl5P/view?usp=sharing']]},
  {title:'Microsoft Certified: Power BI Data Analyst Associate',issuer:'MICROSOFT',links:[['Open certificate','https://drive.google.com/file/d/195WHDxgmqUH-zyp2Lwgx2adOMCfMMai8/view?usp=sharing']]},
  {title:'AWS Academy : Cloud_Foundations',issuer:'AWS ACADEMY',links:[['Open certificate','https://drive.google.com/file/d/1hFzzXKSHXZxS_7iuupUKEo182hgbS8Ou/view?usp=sharing']]},
  {title:'Data Science Essentials with Python',issuer:'DATA SCIENCE',links:[['Certificate','https://drive.google.com/file/d/1juBCF5jzAmpvWKd8fBjTgKQ-ZTl_xi74/view?usp=sharing'],['Additional credential','https://drive.google.com/file/d/1jKR2hWLaYRZbQTWqQAtcUJ7zRXkuuVGq/view?usp=sharing']]},
  {title:'Google Cloud Computing Foundations',issuer:'GOOGLE CLOUD',links:[['Open certificate','https://drive.google.com/file/d/1H1fIxlSi6JuO7Dd7PGfGxr5tYsK6lbfv/view?usp=sharing']]},
  {title:'Green Skills and Artificial Intelligence under Skills4Future Program',issuer:'SKILLS4FUTURE',links:[['Open certificate','https://drive.google.com/file/d/1z86LFwmTMW0DJl5628NxUPTqW3FMJsFs/view?usp=sharing']]}
 ,
  {folder:true,title:'AWS',issuer:'AWS',description:'AWS certificate collection. Open a credential below to view the corresponding document.',links:[['AWS Certificate 01','https://drive.google.com/file/d/12qusJPI-5u8pe32SenoYcgXoh_v0d1X0/view?usp=sharing'],['AWS Certificate 02','https://drive.google.com/file/d/1J7Pav2WvVf83ZH-OxMDMOAze4VmPDqS1/view?usp=sharing'],['AWS Certificate 03','https://drive.google.com/file/d/1KYddovyo8eYGDICWxiwRM5ofaJDRlKRI/view?usp=sharing'],['AWS Certificate 04','https://drive.google.com/file/d/1YgVBFDQrrvuM4cNJMhIBcDtc3aE8dnzs/view?usp=sharing'],['AWS Certificate 05','https://drive.google.com/file/d/1di6tvHUNnTVT_uYJNX8YiFLy9l0Egn3S/view?usp=sharing'],['AWS Certificate 06','https://drive.google.com/file/d/1p-Vc2zRBPD8M28DZBOwuZVtfdiTvCVvM/view?usp=sharing'],['AWS Certificate 07','https://drive.google.com/file/d/1z2DOVivhoT3fdW8CfY3kHoSHLx8ey1G4/view?usp=sharing'],['AWS Certificate 08','https://drive.google.com/file/d/1LG0Zt1ArzMi6gWkgjB3oO3KrVnRR8V1C/view?usp=sharing']]},
  {folder:true,title:'Infosys',issuer:'INFOSYS',description:'Infosys certificate collection. Open a credential below to view the corresponding document.',links:[['Infosys Certificate 01','https://drive.google.com/file/d/12T4dJONEaEZLBxCmDaFt1rTvQoYxMWMl/view?usp=sharing'],['Infosys Certificate 02','https://drive.google.com/file/d/16uJkMEgdJu7P2rxXLnce0DUaK37POAvq/view?usp=sharing'],['Infosys Certificate 03','https://drive.google.com/file/d/1Fb5Bj-iM13hpJ-Rl84Vpi942DDaOJqzg/view?usp=sharing'],['Infosys Certificate 04','https://drive.google.com/file/d/1G7nveisbQ8pCv-S1jbafsSduYfVBYW-x/view?usp=sharing'],['Infosys Certificate 05','https://drive.google.com/file/d/1I6rgoHSAEAMrlKp92BfNw1cSEkb91wgv/view?usp=sharing'],['Infosys Certificate 06','https://drive.google.com/file/d/1KhFA55xvTvwYFRBnpUbnZ8tuwyta8hxZ/view?usp=sharing'],['Infosys Certificate 07','https://drive.google.com/file/d/1c7kbzzKohjGgu9A4ox_v3pjQNLGhVV8r/view?usp=sharing'],['Infosys Certificate 08','https://drive.google.com/file/d/1fuwqz2vJZqjj7q91p4gGYXgxV0SR7qus/view?usp=sharing'],['Infosys Certificate 09','https://drive.google.com/file/d/1lzmo0bbuaLAQR34iBJ1uI63AytaXtWQo/view?usp=sharing'],['Infosys Certificate 10','https://drive.google.com/file/d/1ouWrGXHxV5M5Im18BkjsmUcM4i_bNhOV/view?usp=sharing'],['Infosys Certificate 11','https://drive.google.com/file/d/1ovWEDxGDjKrL8pNlSAEpxMz_E2vXfYlx/view?usp=sharing'],['Infosys Certificate 12','https://drive.google.com/file/d/1pgPYXE7Y8amkJ5ojMCjY8YmzyzgnOQTo/view?usp=sharing'],['Infosys Certificate 13','https://drive.google.com/file/d/1qPMkKpJHl7lpBK3E5xL-lQf5Vzqsg889/view?usp=sharing'],['Infosys Certificate 14','https://drive.google.com/file/d/1s9S_u-aRNovIkz7pIVqBF8AqXtvOlDlp/view?usp=sharing'],['Infosys Certificate 15','https://drive.google.com/file/d/1zk8GA823ZMgfnfa9tFsSFINMiNUHMqbc/view?usp=sharing']]}
 ],
 internships:[
  {type:'VIRTUAL INTERNSHIP',title:'Java Full Stack Developer',description:'Java full-stack development internship experience with the supplied internship certificate.',links:[['Open certificate','https://drive.google.com/file/d/1AKL4jgxlvJGS3DRJRPg0SXa0B_n32r3m/view?usp=sharing']]},
  {type:'JAVA FULL STACK',title:'Java Full Stack',description:'Separate Java Full Stack certificate document supplied for this internship.',links:[['Java Full Stack certificate.pdf - Google Drive','https://drive.google.com/file/d/1D59orsXFs5DcfeS0E3MbTX6V8hKwvvXa/view']]},
  {type:'INTERNSHIP',title:'Artificial Intelligence & Machine Learning',description:'Internship experience in Artificial Intelligence & Machine Learning, with certificate and offer letter supplied.',links:[['Certificate','https://drive.google.com/file/d/1N7uRvG5dWK9_YCTyjw82UFs4jHvbO2t3/view?usp=sharing'],['Offer letter','https://drive.google.com/file/d/1x3kQ9KDUfds4dnpMRCYoscezmEXKfnZI/view?usp=sharing']]},
  {type:'INTERNSHIP',title:'Google Cloud Data Analytics',description:'Internship experience in Google Cloud Data Analytics, with certificate and offer letter supplied.',links:[['Certificate','https://drive.google.com/file/d/14_VXskTea8wGEVCfD4JubDT3azANfdEc/view?usp=sharing'],['Offer letter','https://drive.google.com/file/d/1OpBbFshp8IAh7s1f-9JT46CrPLcwuOnZ/view?usp=sharing']]}
 ],
 highlights:[
  ['01','IIT Madras','B.S. Programming and Data Science student'],['02','Computer Science','B.E. Computer Science student at Mumbai University'],['03','Full Stack','Placement Portal with JWT Authentication and 3-role authorization'],['04','AI + ML','AI-powered analysis and vehicle CO₂ prediction applications'],['05','Kaggle','Three hands-on Kaggle project videos included'],['06','Credentials','Certifications across data science, Power BI, cloud and AI/ML']
 ]
};
